/* Cada idioma é um objeto. As chaves identificam os textos usados no script.js.
 * Os trechos entre chaves, como {preco}, recebem os valores na hora de exibir.
 */
const traducoes = {
  "pt-BR": {
    catalogo: "Catálogo",
    descricaoPagina: "Confira o catálogo de bebidas da {loja}.",
    pularConteudo: "Ir para os produtos",
    idioma: "Idioma",
    idiomaCatalogo: "Idioma do catálogo",
    buscarProdutos: "Buscar produtos",
    informacoesCatalogo: "Informações do catálogo",
    formasPagamento: "Formas de pagamento",
    sobreLoja: "Sobre a loja",
    compartilharCatalogo: "Compartilhar catálogo",
    buscarCatalogo: "Buscar em todo o catálogo",
    fechar: "Fechar",
    categoriasAnteriores: "Ver categorias anteriores",
    maisCategorias: "Ver mais categorias",
    categoriasProdutos: "Categorias de produtos",
    gruposProdutos: "Grupos de produtos",
    produtosCatalogo: "Produtos do catálogo",
    rodapeCatalogo: "Catálogo de produtos",
    fecharJanela: "Fechar janela",
    consultarValor: "Consulte o valor",
    unidade: "Unidade",
    condicaoPix: "Dinheiro / Pix: {preco} cada",
    condicaoCartao: "Débito / Crédito: {preco} cada",
    verDetalhes: "Ver detalhes",
    categoriaVazia: "Nenhum produto cadastrado nesta categoria.",
    resultadosBusca: "Resultados da busca",
    buscaVazia: "Nenhum produto encontrado. Tente outro nome.",
    resultadoUnico: "{quantidade} produto encontrado.",
    resultadoPlural: "{quantidade} produtos encontrados.",
    categoriaQuantidade: "{categoria}: {quantidade} produto(s).",
    emAtualizacao: "Catálogo em atualização.",
    compartilharOffline: "O link para compartilhar fica disponível quando o catálogo está online.",
    linkCopiado: "Link copiado com sucesso",
    copiarEndereco: "Selecione e copie o endereço abaixo:",
    linkCatalogo: "Link do catálogo"
  },
  en: {
    catalogo: "Catalog",
    descricaoPagina: "Browse the drinks catalog from {loja}.",
    pularConteudo: "Skip to products",
    idioma: "Language",
    idiomaCatalogo: "Catalog language",
    buscarProdutos: "Search products",
    informacoesCatalogo: "Catalog information",
    formasPagamento: "Payment methods",
    sobreLoja: "About the store",
    compartilharCatalogo: "Share catalog",
    buscarCatalogo: "Search the entire catalog",
    fechar: "Close",
    categoriasAnteriores: "View previous categories",
    maisCategorias: "View more categories",
    categoriasProdutos: "Product categories",
    gruposProdutos: "Product groups",
    produtosCatalogo: "Catalog products",
    rodapeCatalogo: "Product catalog",
    fecharJanela: "Close window",
    consultarValor: "Ask for the price",
    unidade: "Single unit",
    condicaoPix: "Cash / Pix: {preco} each",
    condicaoCartao: "Debit / Credit: {preco} each",
    verDetalhes: "View details",
    categoriaVazia: "No products in this category yet.",
    resultadosBusca: "Search results",
    buscaVazia: "No products found. Try another name.",
    resultadoUnico: "{quantidade} product found.",
    resultadoPlural: "{quantidade} products found.",
    categoriaQuantidade: "{categoria}: {quantidade} product(s).",
    emAtualizacao: "Catalog being updated.",
    compartilharOffline: "The sharing link will be available when the catalog is online.",
    linkCopiado: "Link copied successfully",
    copiarEndereco: "Select and copy the address below:",
    linkCatalogo: "Catalog link"
  },
  es: {
    catalogo: "Catálogo",
    descricaoPagina: "Consulta el catálogo de bebidas de {loja}.",
    pularConteudo: "Ir a los productos",
    idioma: "Idioma",
    idiomaCatalogo: "Idioma del catálogo",
    buscarProdutos: "Buscar productos",
    informacoesCatalogo: "Información del catálogo",
    formasPagamento: "Formas de pago",
    sobreLoja: "Sobre la tienda",
    compartilharCatalogo: "Compartir catálogo",
    buscarCatalogo: "Buscar en todo el catálogo",
    fechar: "Cerrar",
    categoriasAnteriores: "Ver categorías anteriores",
    maisCategorias: "Ver más categorías",
    categoriasProdutos: "Categorías de productos",
    gruposProdutos: "Grupos de productos",
    produtosCatalogo: "Productos del catálogo",
    rodapeCatalogo: "Catálogo de productos",
    fecharJanela: "Cerrar ventana",
    consultarValor: "Consulta el precio",
    unidade: "Unidad",
    condicaoPix: "Efectivo / Pix: {preco} cada uno",
    condicaoCartao: "Débito / Crédito: {preco} cada uno",
    verDetalhes: "Ver detalles",
    categoriaVazia: "Todavía no hay productos en esta categoría.",
    resultadosBusca: "Resultados de la búsqueda",
    buscaVazia: "No se encontraron productos. Prueba con otro nombre.",
    resultadoUnico: "{quantidade} producto encontrado.",
    resultadoPlural: "{quantidade} productos encontrados.",
    categoriaQuantidade: "{categoria}: {quantidade} producto(s).",
    emAtualizacao: "Catálogo en actualización.",
    compartilharOffline: "El enlace para compartir estará disponible cuando el catálogo esté en línea.",
    linkCopiado: "Enlace copiado correctamente",
    copiarEndereco: "Selecciona y copia la dirección a continuación:",
    linkCatalogo: "Enlace del catálogo"
  }
};

/* Aqui a chave é o texto exato de catalogo.js e o valor é sua tradução.
 * Marcas e volumes são preservados. Textos sem tradução usam o original.
 * Ao cadastrar conteúdo novo, acrescente as traduções nestes objetos.
 */
const textosCatalogo = {
  en: {
    "Catálogo de bebidas": "Drinks catalog",
    "Dinheiro, Pix e cartão": "Cash, Pix and card",
    "Gin": "Gin",
    "Whisky": "Whisky",
    "Vodka": "Vodka",
    "Cerveja": "Beer",
    "Chopp": "Draft beer",
    "Energético": "Energy drinks",
    "Licor": "Liqueur",
    "Drinks prontos": "Ready-to-drink cocktails",
    "Champanhe": "Champagne",
    "Vinho": "Wine",
    "Beats/Ice": "Beats/Ice",
    "Aperitivo": "Aperitif",
    "Cachaça": "Cachaça",
    "Rum": "Rum",
    "Água mineral": "Mineral water",
    "Gelos sabores": "Flavored ice",
    "Refrigerantes/Outros": "Soft drinks/Others",
    "Sucos/Groselhas/Mel/Outros": "Juices/Currant syrups/Honey/Others",
    "Chocolates/Doces": "Chocolates/Sweets",
    "Copos/Descartáveis/Baldes": "Cups/Disposables/Buckets",
    "BEEFEATER 750ml - TRADICIONAL": "BEEFEATER 750ml - ORIGINAL",
    "TANQUERAY TRADICIONAL 750ml": "TANQUERAY ORIGINAL 750ml",
    "JACK DANIELS TRADICIONAL 1L": "JACK DANIELS ORIGINAL 1L",
    "JACK DANIELS MAÇÃ VERDE 1L": "JACK DANIELS GREEN APPLE 1L",
    "GREY GOOSE TRADICIONAL 750ml": "GREY GOOSE ORIGINAL 750ml",
    "GREY GOOSE PERA 750ml": "GREY GOOSE PEAR 750ml",
    "CIROC TRADICIONAL 750ml": "CIROC ORIGINAL 750ml",
    "HEINEKEN LATA 269ml": "HEINEKEN CAN 269ml",
    "RED BULL TRADICIONAL 250ml": "RED BULL ORIGINAL 250ml",
    "RED BULL 250ml - MELANCIA": "RED BULL 250ml - WATERMELON",
    "ENERGÉTICO VIBE 2L": "VIBE ENERGY DRINK 2L",
    "VIBE MAÇÃ VERDE 2L": "VIBE GREEN APPLE 2L",
    "BALLENA COCO 750ml": "BALLENA COCONUT 750ml",
    "LICOR MALIBU COCO 750ml": "MALIBU COCONUT LIQUEUR 750ml",
    "LICOR DON LUIZ 750ml": "DON LUIZ LIQUEUR 750ml",
    "APERITIVO SAINT REMY 750ml": "SAINT REMY APERITIF 750ml"
  },
  es: {
    "Catálogo de bebidas": "Catálogo de bebidas",
    "Dinheiro, Pix e cartão": "Efectivo, Pix y tarjeta",
    "Gin": "Ginebra",
    "Whisky": "Whisky",
    "Vodka": "Vodka",
    "Cerveja": "Cerveza",
    "Chopp": "Cerveza de barril",
    "Energético": "Bebidas energéticas",
    "Licor": "Licor",
    "Drinks prontos": "Cócteles listos para beber",
    "Champanhe": "Champán",
    "Vinho": "Vino",
    "Beats/Ice": "Beats/Ice",
    "Aperitivo": "Aperitivo",
    "Cachaça": "Cachaça",
    "Rum": "Ron",
    "Água mineral": "Agua mineral",
    "Gelos sabores": "Hielos de sabores",
    "Refrigerantes/Outros": "Refrescos/Otros",
    "Sucos/Groselhas/Mel/Outros": "Jugos/Jarabes de grosella/Miel/Otros",
    "Chocolates/Doces": "Chocolates/Dulces",
    "Copos/Descartáveis/Baldes": "Vasos/Desechables/Cubos",
    "BEEFEATER 750ml - TRADICIONAL": "BEEFEATER 750ml - TRADICIONAL",
    "TANQUERAY TRADICIONAL 750ml": "TANQUERAY TRADICIONAL 750ml",
    "JACK DANIELS TRADICIONAL 1L": "JACK DANIELS TRADICIONAL 1L",
    "JACK DANIELS MAÇÃ VERDE 1L": "JACK DANIELS MANZANA VERDE 1L",
    "GREY GOOSE TRADICIONAL 750ml": "GREY GOOSE TRADICIONAL 750ml",
    "GREY GOOSE PERA 750ml": "GREY GOOSE PERA 750ml",
    "CIROC TRADICIONAL 750ml": "CIROC TRADICIONAL 750ml",
    "HEINEKEN LATA 269ml": "HEINEKEN LATA 269ml",
    "RED BULL TRADICIONAL 250ml": "RED BULL TRADICIONAL 250ml",
    "RED BULL 250ml - MELANCIA": "RED BULL 250ml - SANDÍA",
    "ENERGÉTICO VIBE 2L": "BEBIDA ENERGÉTICA VIBE 2L",
    "VIBE MAÇÃ VERDE 2L": "VIBE MANZANA VERDE 2L",
    "BALLENA COCO 750ml": "BALLENA COCO 750ml",
    "LICOR MALIBU COCO 750ml": "LICOR MALIBU COCO 750ml",
    "LICOR DON LUIZ 750ml": "LICOR DON LUIZ 750ml",
    "APERITIVO SAINT REMY 750ml": "APERITIVO SAINT REMY 750ml"
  }
};
